backend:
  name: github
  branch: master
  # repo: myorg/myrepo                    # Path to your GitHub repository
  # base_url: https://oauth.example.org   # Base URL for the OAuth provider

media_folder: "_images"
show_preview_links: true

# Collections managed by the https://github.com/kyodo-tech/decapta generator.